name: RSpec

on:
  push:
  pull_request:

jobs:
  rspec:
    name: Faraday ${{ matrix.faraday }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        faraday:
          - ~> 0.17
          - ~> 1.0
          - ~> 2.0
    env:
      FARADAY_VERSION: ${{ matrix.faraday }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
          bundler-cache: true
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake spec
